require('config.lazy')
require('options')
require('lspSetup')
require('highlights')
require('nvimDebugger')
require('autocommands')

local telescope = require('telescope')
telescope.load_extension('fzf')
telescope.load_extension('file_browser')
telescope.load_extension('undo')
